---
- name: Create AWS EC2 Instances
  hosts: local
  connection: local
  vars:
    action: "creation"
    deploy_env: "dev"
    instances:
      - roboshop
  tasks:
    - name: Print instances name
      ansible.builtin.debug:
        msg: "Instance name is  {{ item }}"
      loop: "{{ instances }}"

    - name: Create EC2 instance
      amazon.aws.ec2_instance:
        name: "{{ item }}-{{ deploy_env }}"
        region: "us-east-1"
        instance_type: "t3.micro"
        security_group: "sg-02a6e8c9e38480783"
        image_id: "ami-0220d79f3f480ecf5"
        tags:
          project: roboshop
          name: "{{ item }}-{{ deploy_env }}"
          env_name: "{{ deploy_env }}"
        wait: true
      loop: "{{ instances }}"
      when: action == "creation"
      register: ec2_instance_out

    - name: Print EC2 instance output
      ansible.builtin.debug:
        msg: "{{ ec2_instance_out }}"
      when: action == "creation"

    - name: get private and public ip from EC2 output
      ansible.builtin.set_fact:
        private_ip: "{{ item.instances[0].private_ip_address }}"
        public_ip: "{{ item.instances[0].public_ip_address }}"
        instance_name: "{{ item.item }}"
      loop: "{{ ec2_instance_out.results }}"
      when: action == "creation"

    - name: Print IP's
      ansible.builtin.debug:
        msg: |
          "PRIVATE IP: {{ private_ip }} \n"
          "PUBLIC IP: {{ public_ip }} \n"
          "INSTANCE NAME: {{ instance_name }} \n"
      when: action == "creation"

    - name: Create Route53 Records
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ item.item }}-{{ deploy_env }}.{{ domain_name }}"     # -- mongodb-dev-dasarikrishna.online
        ttl: 1
        type: A
        value: "{{ private_ip }}"
      loop: "{{ ec2_instance_out.results }}"
      when: action == "creation"

    - name: Create Route53 Records for frontend public
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ roboshop }}-{{ deploy_env }}.{{ domain_name }}"     # -- roboshop-dev-dasarikrishna.online
        ttl: 1
        type: A
        value: "{{ public_ip }}"
      loop: "{{ ec2_instance_out.results }}"
      when: action == "creation" and item.item == "frontend"


    # --- Delete EC2 instance and Route 53 Records based on instance name
    - name: Destroy EC2 instance
      amazon.aws.ec2_instance:
        name: "{{ item }}-{{ deploy_env }}"
        state: absent
        wait: false
      loop: "{{ instances }}"
      when: action == "destroy"

    - name: Delete non frontend Route53 Records
      amazon.aws.route53:
        state: absent
        zone: "{{ domain_name }}"
        record: "{{ item }}-{{ deploy_env }}.{{ domain_name }}"
        type: A
        ttl: 1
      loop: "{{ instances }}"
      when: action == "destroy"

    - name: Delete  frontend Route53 Records
      amazon.aws.route53:
        state: absent
        zone: "{{ domain_name }}"
        record: "{{ roboshop }}-{{ deploy_env }}.{{ domain_name }}"
        type: A
        ttl: 1
      loop: "{{ instances }}"
      when: action == "destroy" and item == "frontend"    




